services:
  database:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:?}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?}
      POSTGRES_DB: ${DATABASE_DB:?}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "$DATABASE_DB" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
